# Generated by Django 4.2.14 on 2024-07-24 18:36

from django.db import migrations, models
import django.db.models.deletion
import pereval.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to=pereval.utils.get_media_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='pereval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='beauty_title',
            field=models.CharField(default='пер. ', max_length=32, verbose_name='Наименование препятствия'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.TextField(blank=True, null=True, verbose_name='Связь'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Другие наименования'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Наименование места'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fam',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otc',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
    ]
